AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.1
  Exclude:
    - '*.spec'
    - 'Rakefile'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/LineLength:
  Max: 190

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Performance/FixedSize:
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
  Exclude:
    - 'config/routes.rb'
    - 'lib/foreman_concrete/engine.rb'
    - 'test/**/*'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'
    - 'app/controllers/concerns/foreman/**/*'
